server:
  tomcat:
    uri-encoding: UTF-8
  port: 9700
spring:
  profiles:
    active: dev
  application:
    name: nacos-test
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
